node {
    def recipientProviders = [
        [$class: 'CulpritRecipientProvider'],
        [$class: 'DeveloperRecipientProvider'],
        [$class: 'RequesterRecipientProvider'],
    ]

    try {
        stage('build') {
            println('so far so good...')
        }
        stage('test') {
            println('A test has failed')
            sh 'exit 1'
        }
    } catch(e) {
        currentBuild.result = "FAILURE";
        def subject = "${env.JOB_NAME} - Build #${env.BUILD_NUMBER} ${currentBuild.result}" 
        def content = '${JELLY_SCRIPT,template="html"}'

        if(recipientProviders != null) {
            emailext(
                body: content, 
                mimeType: 'text/html',
                replyTo: '$DEFAULT_REPLYTO', 
                subject: subject,
                to: "banana@admin.com", 
                recipientProviders: recipientProviders,
                attachLog: true 
                )
        }

        throw e;
    }
}
